### ISSUE TITLE
How to add the autoscroll feature?

### ISSUE THREAD

**Issue by sibascodeking** [adamalbrecht/ngOnboarding#14]
It was not move automatically the current indicator position.

**Comment by adamalbrecht** [comment]
Yeah there's no support for scrolling. You'll have to add a callback function to your step(s).

**Comment by sibascodeking** [comment]
how to add the call back can you help me ?

**Comment by adamalbrecht** [comment]
Actually I take that back - there is no callback on individual steps, only on the final step. Sorry If I caused confusion.

I don't  have time to implement this feature myself, but pull requests are welcome.
