### ISSUE TITLE
Remove Jquery dependency

### ISSUE THREAD

**Issue by jpike88** [adamalbrecht/ngOnboarding#20]
Why on earth would you pull in something like Jquery to do something jqLite can easily do? Talk about dependency bloat.

Using https://github.com/benmarch/angular-ui-tour instead

**Comment by adamalbrecht** [comment]
Pull requests 👍 snarky commentary 👎 

If you have questions about making changes to the codebase or the pull request process, I'd be glad to help. And angular-ui-tour looks really nice. Thanks for bringing it to my attention 😄
