### ISSUE TITLE
Can we publish this as a Bower Package as well?

### ISSUE THREAD

**Issue by mdabydeen** [adamalbrecht/ngOnboarding#9]
Following up from #1, it just seems a little more convenient to be on bower as well.

**Comment by chino23** [comment]
Totally agree. Angular libraries should be in bower. 

@adamalbrecht could you set it up?

**Comment by Urbiwanus** [comment]
+1 
would be awesome to get the package via bower

**Comment by borgogelli** [comment]
+1

**Comment by bobbypriambodo** [comment]
Hi, in case anyone else is wondering, it seems that the package is already on bower. Install it via 
```
bower install ngOnboarding
```
(note the case)

**Comment by mdabydeen** [comment]
@bobbypriambodo you are absolutely correct. Thanks for pointing it out.
